apiVersion: v1
kind: Service
metadata:
  name: pneumonia-service
  labels:
    app: pneumonia-project
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30080 # Optional: specify a node port or leave it out for a random high port to be assigned
  selector:
    app: pneumonia-project